name: CD

on:
  push:
    branches:
      - main   # main 브랜치로 머지될 때 실행

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload jar to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_A_HOST }}
          username: ${{ secrets.EC2_A_USER }}
          key: ${{ secrets.EC2_A_SSH_KEY }}
          source: "./build/libs/*.jar"
          target: "/home/ubuntu/Open-Position-Hub"

      - name: Restart Spring Boot on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_A_HOST }}
          username: ${{ secrets.EC2_A_USER }}
          key: ${{ secrets.EC2_A_SSH_KEY }}
          script: |
            sudo systemctl daemon-reload
            sudo systemctl restart oph
            sudo systemctl status oph --no-pager
